// Transform special needs data from Google Sheet for Convex import
// Run: node import_special_needs.js

const sheetData = [
  // [LastName, FirstName, HomeLang, RideType, PrimeHandicap, Equipment, DisabilityDetails, SeizureProtocol, HandoffReq, Booster, SafetyVest, Camera, RideAsst, TeacherFirst, TeacherLast]
  ["Lopez Contanza", "Alberth", "Spanish", "SOLO", "Autism", "Booster", "", "", "Y", "", "", "", "", "Jessica", "Roads"],
  ["Park", "Alek", "English", "SOLO", "Autism - NV - Extreme Behavior", "Locks", "", "", "", "", "", "", "", "", ""],
  ["Gustin", "Alex", "English", "SOLO", "LD", "Solo", "", "", "", "", "", "", "", "", ""],
  ["O'Hare", "Alexander", "English", "SOLO", "Deaf/Blind/ LD", "Car Seat / Aide", "", "Y", "Y", "", "Y", "Y", "Y", "", ""],
  ["Sandoval", "Amilcar", "English", "Solo", "", "No", "", "", "Y", "", "", "", "Y", "Mimi", "Schalich"],
  ["Soldo", "Anderson", "English", "Solo", "Extreme Behavior", "N", "", "", "", "", "", "", "", "", ""],
  ["Gutierrez", "Andrea/Isabel", "Spanish", "Solo", "LD - Mobility", "Walker/Cane", "", "", "", "", "", "", "", "", ""],
  ["Reyes", "Anthony", "Spanish", "Carpool", "LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Canessa", "Asher", "English", "Carpool", "LD", "Booster", "", "", "", "", "", "", "", "", ""],
  ["Rodas", "Ashley", "English", "SOLO", "Homeless", "N", "", "", "", "", "", "", "", "", ""],
  ["Vargus Lara", "Astrid", "English", "SOLO", "Autism, NV, Blind - Extreme Behavior", "Locks", "", "", "", "", "", "", "", "", ""],
  ["Sanchez", "Aubrey", "English", "Carpool", "LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Dougherty", "Autumn", "English", "SOLO", "LD - NV", "Carseat", "", "", "", "", "", "", "", "", ""],
  ["Madrid", "Avery", "English", "Vanpool", "LD", "No", "", "", "", "", "", "", "", "", ""],
  ["Kernon", "Ben", "English", "Solo - New", "LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Richard", "Ben", "English", "Yes", "LD - NV - Behavioral", "Harness", "", "", "", "", "", "", "", "", ""],
  ["Mora Russell", "Benjamin", "English", "SOLO", "LD - Depression", "N", "", "", "", "", "", "", "", "", ""],
  ["Carson", "Blessing", "English", "Solo", "Homeless", "N", "", "", "", "", "", "", "", "Simone", "Chosse"],
  ["Beltran", "Brandon", "English", "SOLO", "Autism - NV", "Locks", "", "", "", "", "", "", "", "", ""],
  ["Kitterman", "Brandon", "English", "Vanpool", "LD", "No", "", "", "", "", "", "", "", "Samantha", "Rapoport"],
  ["Spooner", "Brian", "English", "SOLO", "Behavioral", "No", "", "", "Y", "", "", "", "Y", "Allison", "Coolidge"],
  ["Anderson", "Brian", "English", "SOLO", "Behavioral - LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Castaneda Diaz", "Briani", "Spanish", "SOLO", "LD, NV, Physically Handicapped", "Car Seat", "", "", "", "", "", "", "", "", ""],
  ["Escudero-Raygoza", "Carlos", "English", "SOLO", "Autistic", "N", "", "", "", "", "", "", "", "", ""],
  ["Perez Chiroy", "Carlos", "Spanish", "Carpool", "Homeless", "Booster", "", "", "", "", "", "", "", "", ""],
  ["Williams", "Caroline", "English", "SOLO", "LD - NV - Extreme", "N", "", "", "", "", "", "", "", "", ""],
  ["Schoenhoeft", "Casey", "English", "SOLO", "LD - Behavioral - Extreme", "Door Locks", "", "", "", "", "", "", "", "", ""],
  ["Compton", "Cashis", "English", "Carpool", "LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Kissane", "Cassidy", "English", "Carpool", "LD", "N", "", "", "", "", "", "", "", "Alison", "Leist"],
  ["Burns", "Clarissa", "English", "Carpool", "Autistic", "N", "", "", "", "", "", "", "", "", ""],
  ["Nguyen", "Curry", "Vietnamese", "Carpool", "Homeless", "N", "", "", "", "", "", "", "", "", ""],
  ["Lee", "Daniel", "English", "SOLO", "Autism - NV", "Locks", "", "", "", "", "", "", "", "", ""],
  ["Luna", "David", "English", "Vanpool", "LD", "No", "", "", "", "", "", "", "", "Ilham", "Stropes"],
  ["Veletzos", "Dominic", "English", "Carpool", "LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Perez Chiroy", "Dulcea", "Spanish", "Carpool", "Homeless", "N", "", "", "", "", "", "", "", "", ""],
  ["Hawkins", "Dylan", "English", "SOLO", "Behavioral", "N", "", "", "", "", "", "", "", "", ""],
  ["Murray", "Edmund", "English", "SOLO", "LD - Behavioral - Extreme", "Vest", "", "", "", "", "", "", "", "", ""],
  ["Perez Terraza", "Edwin", "Spanish", "Carpool", "Homeless", "N", "", "", "", "", "", "", "", "", ""],
  ["Brown-Lewin", "Eliza", "English", "Carpool", "Autism - NV", "Locks", "", "", "", "", "", "", "Y", "", ""],
  ["Riedel", "Eloise", "English", "Carpool", "LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Houck Gonzales", "Emaya", "English", "SOLO", "Currently not going", "N", "", "", "", "", "", "", "", "", ""],
  ["Freedman", "Emma", "English", "Carpool", "LD", "N", "", "", "", "", "", "", "", "Kimberly", "Rico"],
  ["Mendoza Martinez", "Emma", "Spanish", "Carpool", "LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Aguirre-Veliz", "Eric", "English", "Carpool", "Autistic", "N", "", "", "", "", "", "", "", "", ""],
  ["Luke", "Ethan", "English", "Carpool/Split District", "Autism", "N", "Autism", "", "", "", "", "", "", "Jade", "Martin"],
  ["Compton", "Evander", "English", "Carpool/Split District", "Autism", "N", "", "", "", "", "", "", "", "", ""],
  ["Wyllie", "Gabriella", "English", "Carpool", "LD", "N", "", "", "", "", "", "", "", "Sonya", "Carillo"],
  ["Moran", "Geffen", "English", "SOLO", "LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Campos", "Genesis", "English", "Carpool", "Homeless", "N", "", "", "", "", "", "", "", "", ""],
  ["Mitchell", "Getty", "English", "Carpool", "Non Verbal - LD", "N", "", "", "", "", "", "", "", "Whitney", "Okeefe"],
  ["Medrano", "Hansel", "English", "SOLO", "LD, Autism - Exteme", "N", "", "", "", "", "", "", "", "", ""],
  ["Matson", "Helaina", "English", "SOLO", "LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Purdy", "Hudson", "English", "SOLO", "Autism - NV - Extreme", "Solo", "", "", "", "", "", "", "", "Joseph", "Karson"],
  ["Newton", "Hunter", "English", "SOLO", "Autism - NV - Extreme Behavior", "Harness", "", "", "", "", "", "", "", "", ""],
  ["Constantino", "Huxley", "Spanish", "SOLO", "Autism, NV, - Extreme Behavior", "Harness, Flight Risk", "", "", "", "", "", "", "", "", ""],
  ["Camposeco", "Ihan", "Spanish", "Carpool", "Homeless", "Booster", "", "", "", "", "", "", "", "", ""],
  ["Rettberg", "Isaac", "English", "SOLO", "LD - Behavioral - Extreme", "N", "", "", "", "Y", "", "", "", "Jolene", "Yee - Director"],
  ["Sihra", "Isadora", "English", "SOLO", "LD - NV - Behavioral - Extreme", "Solo", "", "", "", "", "", "", "", "", ""],
  ["Nathanson", "Jack", "English", "SOLO", "LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Moore", "Jainagil", "English", "SOLO", "LD - NV", "Carseat", "", "", "", "", "", "", "", "", ""],
  ["Ott", "James", "English", "W/C Van", "Non Verbal - Handicap - Autism", "Wheelchair", "", "", "", "", "", "", "", "", ""],
  ["Lapic", "Jamie", "English", "SOLO", "LD", "Cane/walker", "", "", "", "", "", "", "", "", ""],
  ["Banducci-Camona", "Jasmin", "English", "SOLO", "LD", "N", "", "", "", "", "", "", "", "Steve", "Maldonado"],
  ["Shelley", "Jesse", "English", "SOLO", "LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Mendoza", "Joey", "English", "Carpool", "LD - Behavioral - Extreme", "N", "", "", "", "", "", "", "", "", ""],
  ["Flores", "Jose", "English", "SOLO", "Behavioral - Drugs", "N", "", "", "", "Y", "", "", "", "Jolene", "Yee - Director"],
  ["de La Cruz", "Josseph", "Spanish", "SOLO", "CP - LD, Non English Speaking", "Wheelchair", "", "", "", "", "", "", "", "", ""],
  ["de Leon Campos", "Junior", "English", "Carpool", "Homeless", "N", "", "", "", "", "", "", "", "", ""],
  ["McFarland", "Kaiden", "English", "SOLO", "Private", "N", "", "", "", "", "", "", "", "", ""],
  ["Soriano Vasquez", "Kimberly", "Spanish", "Carpool", "Homeless", "N", "", "", "", "", "", "", "", "", ""],
  ["Gillard", "Lachlan", "English", "SOLO", "Autism - Extreme", "Locks", "", "", "", "", "", "", "", "", ""],
  ["Lopez", "Leivi", "Spanish", "SOLO", "Behavioral - LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Goldberg", "Levi", "Spanish", "SOLO", "LD, Extreme Behavior", "No", "", "", "Y", "", "", "", "Y", "Mimi", "Schalich"],
  ["Sanford", "Mae", "English", "SOLO", "MD, LD, Autism - Exteme", "Solo", "", "", "", "", "", "", "Y", "", ""],
  ["Price", "Makai", "English", "Carpool", "LD, Extreme Behavior", "No", "", "", "", "", "", "", "Y", "Allison", "Coolidge"],
  ["Rosenblum", "Mara", "English", "Carpool", "Autism - NV - Handicaped", "Carseat", "", "", "", "", "", "", "", "", ""],
  ["Sanchez", "Mateo", "English", "SOLO", "Autism - Must be walked to class - Runner", "PM Transport to Terra Linda High School", "", "", "", "", "", "", "", "Annie", "Boight"],
  ["Munene", "Mawangi Gabriel", "English", "SOLO", "Tuesday Thursday Fridays PM ONLY", "Carseat", "", "", "", "", "", "", "", "", ""],
  ["Sontay Hernandez", "Melanie", "Spanish", "Carpool", "Autism - NV", "Carseat", "", "", "", "", "", "", "", "", ""],
  ["Giacoppa", "Michaela", "English", "Carpool", "Autism - NV - Extreme", "Locks", "Micaela may need assistance in & Out of the vehicle", "", "", "Y", "", "", "Y", "", ""],
  ["Jaffee", "Milo", "English", "Carpool", "LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Schaefer", "Milo", "English", "Carpool/Split District", "Autism", "N", "", "", "", "", "", "", "", "", ""],
  ["Radar", "Moses", "English", "SOLO", "NV, Autism, Physically Handicaped", "Gate Belt, Wheelchair", "", "", "", "", "", "", "", "Cindy", "Evans"],
  ["Bryan", "Myles", "English", "SOLO", "Autism", "Car Seat", "", "", "", "", "", "", "", "Carla", "Echeveria"],
  ["Espantzay", "Mynor Suy", "English", "SOLO", "Homeless", "N", "", "", "", "", "", "", "", "", ""],
  ["Debisschop", "Nicholas", "English", "Carpool", "LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Nathanson", "Olivia", "English", "SOLO", "None", "N", "", "", "", "", "", "", "", "", ""],
  ["Delay", "Penny", "English", "Yes", "NV/Austism/Needs Transfer Assistance", "Car Seat", "", "", "", "Y", "", "Y", "Y", "Kate", "Mansour"],
  ["Viotay", "Pharoah", "English", "SOLO", "LD - flight risk difficul load - Booster Seat", "Carseat", "", "", "", "", "Y", "", "", "", ""],
  ["Crawford-Green", "Rashaun", "English", "SOLO", "LD - NV - Behavioral - Extreme", "Solo - Male Driver", "", "", "", "", "", "", "", "", ""],
  ["Danziger", "Reese", "English", "SOLO", "None", "N", "", "", "", "", "", "", "", "", ""],
  ["Goldstien", "Rex", "English", "SOLO", "Autism - NV - Extreme", "Solo", "", "", "", "", "", "", "", "", ""],
  ["Reyes-Vela", "Richardo", "Spanish", "SOLO", "LD, Extreme Behavior", "No", "", "", "", "", "", "", "", "Allison", "Coolidge"],
  ["Hurd", "Riely", "English", "SOLO", "Autism -Extreme - Flight Risk", "N", "", "", "", "", "", "", "", "", ""],
  ["Rodas", "Riely", "English", "SOLO", "Autism - Joana", "N", "", "", "", "", "", "", "", "", ""],
  ["Reible", "Rosalie", "English", "SOLO", "LD, Physically Handicapped", "Locks", "", "", "", "", "", "", "", "", ""],
  ["Klein", "Rowan", "English", "SOLO", "LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Ramirez-Preciado", "Roy", "Spanish", "SOLO", "MD, LD, Autism - Exteme", "Wheelchair", "", "", "", "", "", "", "", "", ""],
  ["Massey", "Rylan", "English", "SOLO", "LD - Behavioral - Foul Language", "Door Locks", "", "", "", "", "", "", "Y", "", ""],
  ["Glasser", "Sam", "English", "Carpool", "LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Toussaint", "Samaile", "English", "Carpool", "LD", "N", "Severe", "", "", "", "", "", "", "", ""],
  ["Greenstone", "Samantha", "English", "SOLO", "LD", "N", "", "", "", "", "", "", "", "Ryan", "Donahue"],
  ["Cloney", "Shannon", "English", "SOLO", "Autism", "N", "", "", "", "", "", "", "", "", ""],
  ["Mackay", "Shanti", "English", "SOLO", "LD", "N", "", "", "", "", "", "", "Y", "Owen", "Latham"],
  ["Beckman", "Siena", "English", "SOLO", "LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Pratt", "Skylar", "English", "SOLO", "NEW", "N", "", "", "", "", "", "", "", "", ""],
  ["Ingoldsby", "Sophia", "English", "Solo-Private", "Autism", "N", "", "", "", "", "", "", "", "", ""],
  ["Fulvio", "Soren", "English", "SOLO", "LD - NV - Behavioral - Extreme", "Door Locks SOLO", "", "", "", "", "", "", "", "", ""],
  ["Sansing", "Tallulah", "English", "SOLO", "LD, Autism, NV", "N", "", "", "", "", "", "", "", "", ""],
  ["Moore", "Terrance", "English", "SOLO", "Behavioral - LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Traeger", "Thomas", "English", "Carpool", "LD", "No", "", "", "", "", "", "", "", "Jolene", "Yee"],
  ["Lewis", "Tia", "English", "Carpool", "Autism - NV", "N", "", "", "", "", "", "", "", "", ""],
  ["Sturm", "Toby", "English", "Carpool", "LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Stuart", "Twila", "English", "Carpool", "LD", "N", "", "", "", "", "", "", "", "", ""],
  ["Bell", "Violet", "English", "Carpool", "LD", "N", "", "", "", "", "", "", "", "Amy", "Louton"],
  ["Gonzalez Hernandez", "Wasley", "Spanish", "W/C VAN", "Non Verbal - Handicap - Autism", "Wheelchair", "", "", "", "", "", "", "", "", ""],
  ["Sims", "Will", "English", "Solo/Aide", "Autism", "Harness", "", "", "", "Y", "", "", "Y", "John", ""],
  ["DeGrassi", "Will", "English", "Carpool", "LD, NV, Physically Handicapped", "Car Seat", "", "", "", "", "", "", "", "", ""],
  ["Maldonado", "Yadiel", "Spanish", "W/C VAN", "Non Verbal - Handicap - Autism", "Wheelchair", "", "", "", "", "", "", "", "", ""],
  ["Martinez Sanchez", "Yolkin", "Spanish", "SOLO", "Homeless", "Booster", "", "", "", "", "", "", "", "", ""]
];

// Transform to import format
const records = sheetData.map(r => ({
  childFirstName: r[1].trim(),
  childLastName: r[0].trim(),
  homeLanguage: r[2].trim() || undefined,
  rideType: r[3].trim() || undefined,
  primeHandicap: r[4].trim() || undefined,
  equipment: r[5].trim() || undefined,
  disabilityDetails: r[6].trim() || undefined,
  seizureProtocol: r[7].trim() || undefined,
  handoffReq: r[8].trim() || undefined,
  booster: r[9].trim() || undefined,
  safetyVest: r[10].trim() || undefined,
  camera: r[11].trim() || undefined,
  rideAssistant: r[12].trim() || undefined,
  teacherFirstName: r[13]?.trim() || undefined,
  teacherLastName: r[14]?.trim() || undefined
})).filter(r => r.childFirstName && r.childLastName);

// Output as JSON for convex run command
console.log(JSON.stringify(records));
